### ISSUE TITLE
Releases tag

### ISSUE THREAD

**Issue by yursan9** [shuLhan/hunspell-id#1]
Bisakah menambahkan _release tag_ ?
Saya ingin memaketkan ini untuk [Solus Project](https://solus-project.com/), tapi tidak
diperbolehkan jika langsung mengambil dari `master`.

**Comment by shuLhan** [comment]
Selesai: https://github.com/shuLhan/hunspell-id/releases/tag/v0.1

**Comment by yursan9** [comment]
Tagnya gak bisa sama kaya versi yang di README? Di depan tulisannya versi 2.0. Nanti di repo versinya jadi 0.1 kaya di tag. Oh iya, makasih sudah dikasih tag. Sepi bener reponya. 😄

**Comment by shuLhan** [comment]
Di README-nya sudah versi 2 ternyata ya. Aku ganti jadi v2.1, biar konsisten.

> Di depan tulisannya versi 2.0. Nanti di repo versinya jadi 0.1 kaya di tag. 

Harusnya versi di repo sama dengan tag.

> Sepi bener reponya. 😄

Kalau ada masukan lagi, silahkan di bikin _issue_ atau _pull-request_ biar ramai :)

**Comment by yursan9** [comment]
Oke kalau lagi sempet nanti nambah kata ke dict dari KBBI baru. 👍

**Comment by yursan9** [comment]
Sudah diterima ke repo https://git.solus-project.com/packages/hunspell-id/
