### ISSUE TITLE
Beberapa kata bentukan masih dianggap salah

### ISSUE THREAD

**Issue by atriwidada** [shuLhan/hunspell-id#4]
contoh kata yang dianggap salah eja:
disenandungkan (kata dasar 'senandung' sudah ada di kamus)
pelantun (kata dasar 'lantun' sudah ada di kamus)

apakah isi id_ID.aff belum komplit atau salah? saran ejaan untuk 'pelantun' diantaranya adalah 'pe-lantun' dan 'pe lantun', sedangkan saran ejaan untuk disenandungkan antara lain adalah 'senandungan'

**Comment by shuLhan** [comment]
> apakah isi id_ID.aff belum komplit atau salah?

Belum komplit pak. Bisa diubah dan di-_PR_. Saya cek di KBBI web, kata "pelantun" belum ada [1].

[1] https://kbbi.web.id/pelantun
