### ISSUE TITLE
Add support for Lucene CIRCUMFIX declaration

### ISSUE THREAD

**Issue by Epenjehem** [shuLhan/hunspell-id#6]
I tried to use Hunspell ID for [ElasticSearch](https://www.elastic.co/)
- https://github.com/shuLhan/hunspell-id/blob/master/id_ID.aff
- https://github.com/shuLhan/hunspell-id/blob/master/id_ID.dic

During the initiation, error occurred with message 

> Illegal CIRCUMFIX declaration

It turns out the CIRUMFIX declaration does not pass these checking
https://github.com/apache/lucene-solr/blob/master/lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/Dictionary.java#L340-L344

To add support for this, we need to move the comment declaration in https://github.com/shuLhan/hunspell-id/blob/master/id_ID.aff#L41-L42 to another line, example:

```
# untuk bentuk awalan-akhiran terikat (ber-an)
CIRCUMFIX A1 
# jenis membesituakan (jangan besitua tersendiri)
NEEDAFFIX A2
```

**Comment by shuLhan** [comment]
@Epenjehem does this comment affect only CIRCUMFIX or it also the comments in the rest of file, for example line 46, 50, 54, and so on?

**Comment by Epenjehem** [comment]
@shuLhan during the test, the error only happen during CIRCUMFIX & NEEDAFFIX
After I modified the comment position, no error was thrown and I can use it.

To be more save, you can refer to these lines:
https://github.com/apache/lucene-solr/blob/master/lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/Dictionary.java#L340-L376

Basically when you put a comment inline, it failed at this logic
`if (parts.length != 2) {`

So to answer your question

> does this comment affect only CIRCUMFIX or it also the comments in the rest of file, for example line 46, 50, 54, and so on?

Fo the current affix, the error only because the CIRCUMFIX & NEEDAFFIX comment style

**Comment by shuLhan** [comment]
@Epenjehem I have fix it in latest commit. Please try and re-open if the issue is still exist. Thank you.
